Allow WCS merging to work without loading all data at once
astropy/reproject pull request #242
Opened 2020-10-12 17:41 UTC by pkgw

For `find_optimal_celestial_wcs`, we only really need the input image shape, not the actual data. Modify the support infrastructure to allow computation in this regime. This allows us to solve for the optimal WCS even in cases where we wouldn't be able to hold all of the input images in memory at the same time.

2020-10-12 17:54 UTC, pkgw commented
Numerous CI failures but they seem to be unrelated to this PR, I think. @astrofrog is this a known situation?

2020-10-13 13:22 UTC, Cadair commented
oh my what are those test faliures! :see_no_evil:

2020-10-16 14:32 UTC, pkgw commented
@Cadair Not a ton of activity on this repo lately ... do you know who might know how to fix up the CI?

2020-10-16 15:21 UTC, Cadair commented
I can add it to my stack, but I also don't have a huge amount of time. @astrofrog might be able to take a look though, think he said he might be swinging back to reproject soon.

2020-10-16 20:36 UTC, astrofrog commented
I'll take a look now

2020-10-17 03:25 UTC, astrofrog commented
@pkgw - can you rebase? The CI should be fixed now. Thanks!

2020-10-20 23:17 UTC, pkgw commented
Looks like I need to beef up the test coverage ...

2020-10-26 22:20 UTC, pkgw commented
I've added some tests that should hopefully get the code coverage happy again. In so doing I did discover an implementation mistake, so yay tests!

2020-10-27 03:09 UTC, pkgw commented
Figuring out the best approach to the Linux docs build. Meanwhile, the macOS doc build seems to be failing for an unrelated reason?

2020-10-28 20:29 UTC, pkgw commented
OK, I think the only remaining issue is this MacOS docs thing. @astrofrog @Cadair any idea what's up here? Naively it looks like some kind of binary problem in Numpy. Presumably associated with a new release if it just started happening?

```
  File "./reproject/spherical_intersect/setup_package.py", line 3, in <module>
    import numpy as np
  File "/Users/runner/work/1/s/.tox/.package/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

2020-10-28 20:33 UTC, pkgw commented
Ah: https://github.com/numpy/numpy/issues/15947

2020-10-28 21:25 UTC, pkgw commented
Finally green! Let me know if you'd like to see anything else before merging.

Once this is merged, would you mind putting out a new release with the new API feature? I'd like to be able to start using this in [toasty](https://github.com/WorldWideTelescope/toasty/).

2020-10-30 15:19 UTC, astrofrog requested changes
Looks good! Just one comment below.

2020-10-30 15:19 UTC, astrofrog commented on reproject/mosaicking/wcs_helpers.py
> +def find_optimal_celestial_wcs(input_shapes, frame=None, auto_rotate=False,
I'm hesitant to change the argument name as I've seen cases where the first arg is passed as a kwarg - can you change the name back?

2020-10-30 15:23 UTC, astrofrog commented
This also needs a changelog entry

2020-10-30 15:43 UTC, pkgw commented
OK, this should do it ...

2020-10-30 19:33 UTC, astrofrog approved these changes
Looks good, thanks!

2020-10-30 19:33 UTC, merged